server:
  port: 8082

spring:
  application:
    name: benedict-consumer
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://210.89.181.20:3306/zaggle
    username: zaggle_test
    password: zg123456
    hikari.connection-timeout: 60000
    hikari.maximum-pool-size: 5
  jpa.hibernate.ddl-auto: create-drop
file:
  path: output

# logging.level.org.springframework: debug
